version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: device_postgres
    restart: always

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: device_db

      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - device_pg_data:/var/lib/postgresql/data

    networks:
      - device_net

networks:
  device_net:

volumes:
  device_pg_data: